### ISSUE TITLE
Suggestion: Teleport player to a safe spot at respawn

### ISSUE THREAD

**Issue by ghost** [GabrielFJunkes/MultipleBedSpawn#12]
I think it would be nice if the player is teleported high into the sky before the bed pick GUI gets shown.
It would prevent players getting spawn trapped at the world spawn and it would also look nicer when you have a neutral background instead of the world spawn (my opinion).

**Comment by GabiJunkes** [comment]
I would have to save the player's location when they spawn and then teleport them to the sky. But I like the idea.
I am having a busy week, so when I have time I will start making it.

**Comment by GabiJunkes** [comment]
Implemented by #15
