### ISSUE TITLE
Limit beds with permissions 

### ISSUE THREAD

**Issue by DLmass** [GabrielFJunkes/MultipleBedSpawn#17]
Would have been very good if it was possible to limit the amount of beds for each individual player by permissions.

multiplebedspawn.beds.1
multiplebedspawn.beds.2

Etc..

**Comment by GabiJunkes** [comment]
Seems useful. I will work on that.

**Comment by GabiJunkes** [comment]
Done in #19. Find any bugs you can report them with another issue. Thanks for the feature request!
Added on README how to use it.
