### ISSUE TITLE
Incompability with random respawn plugin

### ISSUE THREAD

**Issue by andriiqx** [GabrielFJunkes/MultipleBedSpawn#25]
I have plugins on random coords after respawn (anarchy server), where you can put min-max X and Z coordinates, and after respawn, player will have random position. But, after installing 1.9, player without bed always spawns on world spawn coords. Can you fix it?

(Here is example of that plugin so you can test it)
[AnarchySpawn (1).zip](https://github.com/GabrielFJunkes/MultipleBedSpawn/files/13788475/AnarchySpawn.1.zip)

**Comment by GabiJunkes** [comment]
I will have a look tomorrow, try to disable spawn-on-sky, so players spawn location is not changed. This should fix it while i create a patch.

**Comment by GabiJunkes** [comment]
Sorry I could not look in to it. If the config I told you did not work open another issue, and I will work when I have some time. I will be closing this.

**Comment by andriiqx** [comment]
> Sorry I could not look in to it. If the config I told you did not work open another issue, and I will work when I have some time. I will be closing this.

it's okay, i fixed it thanks to your suggestion
