### ISSUE TITLE
Multiworld support

### ISSUE THREAD

**Issue by mrdeniska1234** [GabrielFJunkes/MultipleBedSpawn#26]
If the spawn point is in a different world than the death point - when selecting "TO SPAWN" the player is teleported to the wrong location, according to the spawn coordinates, but in the world where death occurred

**Comment by GabiJunkes** [comment]
This is the intended behavior. But I could work on a feature to address that.

**Comment by GabiJunkes** [comment]
Would listing all the worlds spawns to select from solve this? Do you think of a more elegant way?
Or maybe primary worlds, so only selected worlds spawns appear, or use the whitelist config option already implemented to select the worlds to choose from. I am open to suggestions.

**Comment by mrdeniska1234** [comment]
I would like that when pressing the "SPAWN" button, the player would teleport to a random point, or that the player would use the /rtp command after pressing, or any other command installed in the config

**Comment by GabiJunkes** [comment]
Does /rtp teleport to a random world as well?
Would a run command on SPAWN click work for you? I am not quite following what you want exactly.

**Comment by mrdeniska1234** [comment]
I have multiworld, lobby, world, ender and nether. Static spawn point place on lobby, and i have /rtp command, this command random teleport to random point in world "world". 
If we take into account the idea of ​​the “spawn” button from RUST, then the player should execute the command /rtp when clicking the spawn button in your interface, or teleport to a static spawn located in the lobby.
If I die in the nether world now and press the spawn button, I will end up in an incomprehensible place in hell, and not in the normal world, which is strange.

**Comment by GabiJunkes** [comment]
The nether one is a bug (it is not intended), I will work on fixing this and work on your idea.
Thanks for the feedback, it might take some time as I am a little busy.

**Comment by GabiJunkes** [comment]
Done and tested, in #30.
