### ISSUE TITLE
UnsupportedClassVersionError 

### ISSUE THREAD

**Issue by Alfuego** [GabrielFJunkes/MultipleBedSpawn#3]
I have tried in many ways to make it load but it keeps giving me the same error even if I have the maximum Java version of the hosting.

"org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/gabrielfj/multiplebedspawn/MultipleBedSpawn has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 61.0"

I need help with this. Thank you

**Comment by GabiJunkes** [comment]
I released a version with java 17.
Let me now if it works, so i can close this issue.

**Comment by GabiJunkes** [comment]
Should be fixed!
