### ISSUE TITLE
MultipleBed : Config

### ISSUE THREAD

**Issue by PATRONIOO** [GabrielFJunkes/MultipleBedSpawn#4]
Hi, I need to completely translate the plugin first, but I already understood how to do this, but I'm interested in how to change the description of the items, I need to remove the coordinates from them I found in the line of code "X:" but I didn't understand anything, please help or send an option with the coordinates already cut down

**Comment by GabiJunkes** [comment]
Hey, thanks for the feedback, would an option for disabling what goes in the bed description work?
So you can disable the world name that the bed is in and another option to disable displaying the coords of the bed, so if you disable both, it would only display the cooldown.

**Comment by GabiJunkes** [comment]
Done, I added what I said, I am just waiting on your feedback about my comment to merge the pr.
I am also waiting for your translation, so I don't need to make another release, the new feature + your translation can be pushed together to 1.4 release.

**Comment by PATRONIOO** [comment]
Thank you very much! I'm going to try to use it now, I hope everything will be as I wanted, and I'll immediately send you a translation in Russian, there are a few lines like "Beds" "Cooldown {1}" and so on, but I'll still send

**Comment by PATRONIOO** [comment]
https://drive.google.com/file/d/1IXql4Bz80djACOV3NOGifetDNtQftEm6/view?usp=share_link 
Plugin (Locale Russian)
