### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by PATRONIOO** [GabrielFJunkes/MultipleBedSpawn#6]
Hi, this is my translation into Russian, I know that you will leave the author, so please just leave my discord: "PATRON#7072", and I would also like to ask you to join me as friends, we can discuss how to improve your plugin, I can give ideas and, however, translate your plugins to Russian language

Dowloand ruRU.yml https://drive.google.com/file/d/1IXql4Bz80djACOV3NOGifetDNtQftEm6/view?usp=share_link

**Comment by GabiJunkes** [comment]
Thank you for the translation and feedback, for future feedback you can just open another git issue, so the discussion is public. I am not really a fan of discord for public relations, so I'll stick with github discussions.
Added in [V1.4](https://github.com/GabrielFJunkes/MultipleBedSpawn/releases/tag/V1.4)
