### ISSUE TITLE
Invincibility bug

### ISSUE THREAD

**Issue by Ashparty** [GabrielFJunkes/MultipleBedSpawn#8]
Server version: 1.19.3
Plugin version: V1.3 (Java 17 version)

Issue: Players who leave the server in the bed select menu rejoin with invincibility and invisibility

How to recreate: Die, respawn and stay in the bed selector menu, then leave the server (through alt+f4 or similar methods), restart your game and join the server, you are now completely invincible and can still interact with everything until you die through a command.

**Comment by GabiJunkes** [comment]
That is something I did not think about, but makes sense. I'll start working on that, should be easy.

**Comment by Ashparty** [comment]
Thanks!
